### ISSUE TITLE
Access to the paper

### ISSUE THREAD

**Issue by kanghui-learning** [PKUliujl/GeoPacker#1]
Hi Liu:

Congratulations on your great work, I'm interested in more details about GeoPacker, but I cannot download the paper. Could you please send me a version of your article? I would appreciate your help.

**Comment by PKUliujl** [comment]
Thanks for your interest in our recently published paper GeoPacker. See details from the attach file.
[Protein Science - 2022 - Liu - GeoPacker  a novel deep learning framework for protein side‐chain modeling.pdf](https://github.com/PKUliujl/GeoPacker/files/9949682/Protein.Science.-.2022.-.Liu.-.GeoPacker.a.novel.deep.learning.framework.for.protein.side.chain.modeling.pdf)

**Comment by kanghui-learning** [comment]
Thanks!
